language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
notifications:
  slack:
    on_success: always
  email:
    - charinda04@gmail.com 
    - jdinith72@gmail.com 
  on_failure: always
  on_success: always
